[build]
  base    = "."
  command = "CI= npm run build"
  publish = "public"

[context.develop]
  [[headers]]
    for = "/*"
    [headers.values]
      X-Robots-Tag = "noindex"
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"